export const imageConstants = {
    SplashScreenLogo : require('../assets/images/splash_screen_logo.png'),
    Weight : require('../assets/images/weight.jpg'),
    caleriesIcon : require('../assets/images/calories_icon.png'),
    proteinIcon : require('../assets/images/protein_icon.png'),
    carbsIcon : require('../assets/images/carbs_icon.png'),
    fatIcon : require('../assets/images/fats_icon.png'),
    pescatarian : require('../assets/images/pescatarian.png'),
    editPencil : require('../assets/images/edit_pencing.png'),
    vegan : require('../assets/images/vegan.png'),
    vegetarian : require('../assets/images/vegetarian.png'),
    orange : require('../assets/images/orange.png'),
    sun : require('../assets/images/sun.png'),
    rocket : require('../assets/images/rocket.png'),
    yoga : require('../assets/images/yoga.png'),
    fish : require('../assets/images/fish.png'),
    WeightTransition : require('../assets/images/weight_transition.jpg'),
    BackArrow : require('../assets/images/back_arrow.png'),
    LowFrequencyIcon: require('../assets/images/frequency_low.png'),
    MedFrequencyIcon: require('../assets/images/frequency_medium.png'),
    HighFrequencyIcon: require('../assets/images/frequency_high.png'),
    ThumbsUpIcon: require('../assets/images/thumbs_up.png'),
    ThumbsDownIcon: require('../assets/images/thumbs_down.png'),
    ActivityLowIcon: require('../assets/images/frequency_low.png'),
    ActivityMediumIcon: require('../assets/images/frequency_medium.png'),
    ActivityHighIcon: require('../assets/images/frequency_high.png'),
    MealThreeIcon: require('../assets/images/meal_three.png'),
    MealFourIcon: require('../assets/images/meal_four.png'),
    MealFiveIcon: require('../assets/images/meal_five.png')
};